version: '3.8'

services:
  frontend:
    image: node:22
    environment:
      NODE_ENV: development
      PORT: 80
    entrypoint: >
      /bin/sh -c "
        cd /app;
        npm ci;
        npm start;
      "
    volumes:
      - ./frontend:/app

  backend:
    build: backend/
    image: ghcr.io/warehog/podej-dalej/pd-backend:develop
    ports:
      - 3001:3000
    entrypoint: >
      /bin/sh -c "
        rails db:migrate;
        bundle exec rails server -b 0.0.0.0;
      "
    environment:
      RAILS_ENV: development
      DB_ADAPTER: postgresql
      DB_HOST: db
      DB_NAME: db_name
      DB_USER: db_user
      DB_PASS: db_pass
      STORAGE_SERVICE: local
      MINIO_BUCKET: default
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY_ID: administrator
      MINIO_SECRET_ACCESS_KEY: administrator


  db:
    image: postgres:15
    environment:
      DB_ADAPTER: postgresql
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  proxy:
    image: caddy
    ports:
      - 6776:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  minio:
    image: minio/minio:RELEASE.2020-07-24T22-43-05Z
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - 'minio:/data'
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=administrator
      - MINIO_SECRET_KEY=administrator
      - MINIO_DEFAULT_BUCKETS=default
  
  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 4;
      /usr/bin/mc alias set myminio http://minio:9000 administrator administrator;
      /usr/bin/mc mb myminio/default;
      exit 0;
      "

volumes:
  db_data:
  minio:
