apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: pd-dev-ns
spec:
  clusterIP: None   # This makes the service headless.
  selector:
    app: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: pd-dev-ns
spec:
  serviceName: db    # Must match the governing (headless) service name.
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: db_name
            - name: POSTGRES_USER
              value: db_user
            - name: POSTGRES_PASSWORD
              value: db_pass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pd-dev-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pd-dev-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
