name: CI

on:
  pull_request:
    branches: [ "prod", "develop" ]

  push:
    branches: [ "prod", "develop" ]

jobs:
  build-frontend:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 5: Set up Node for the React frontend
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      # Step 6: Install Node dependencies
      - name: Install Node dependencies
        run: |
          cd frontend
          npm install
      
      # Step 7: Build React app
      - name: Build React app
        run: |
          cd frontend
          npm run build

  build-backend:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      # Step 3: Install Ruby dependencies (Rails backend)
      - name: Install Ruby dependencies
        run: |
          cd backend
          bundle install