name: test & build

on:
  pull_request:
    branches: [ "prod", "develop" ]

  push:
    branches: [ "prod", "develop" ]

jobs:
  verify-frontend:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 5: Set up Node for the React frontend
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
      
      # Step 6: Install Node dependencies
      - name: Install Node dependencies
        run: |
          cd frontend
          npm install

  verify-backend:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      # Step 3: Install Ruby dependencies (Rails backend)
      - name: Install Ruby dependencies
        run: |
          cd backend
          bundle install
  
  package-frontend:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 5: Set up Node for the React frontend
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      # Step 7: Build React app
      - name: Build React app
        run: |
          cd frontend
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: front_app
          path: |
            frontend/build/*

  package-backend:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: 
      - verify-frontend
      - verify-backend
    steps:
      # Step 1: Check out code
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/myapp
          docker build -t $IMAGE_NAME:latest backend
          docker push $IMAGE_NAME:latest

  
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    environment: prod
    runs-on: ubuntu-latest
    needs: 
      - package-backend
      - package-frontend
    steps:
      - name: Download frontend files
        uses: actions/download-artifact@v4
        with:
          name: front_app

      - name: Deploy React via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: front_app
          server-dir: /home/admin/public_html

      - name: SSH to Swarm manager and deploy
        uses: sagebind/docker-swarm-deploy-action@v1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          stack_file: stack.yml
          stack_name: podej_dalej_prod
      