name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Set up Ruby (change to your required version)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      
      # 3. Install Ruby dependencies for the backend
      - name: Install Ruby dependencies
        run: |
          cd backend
          bundle install
      
      # 4. Run backend tests (optional step; remove if not needed yet)
      - name: Run Rails tests
        run: |
          cd backend
          # Prepare DB for test environment (if you use a DB)
          bundle exec rails db:create db:migrate RAILS_ENV=test
          # Run tests (replace with your test command)
          bundle exec rspec

      # 5. Set up Node (change to the version you need)
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      # 6. Install Node dependencies for the frontend
      - name: Install Node dependencies
        run: |
          cd frontend
          npm install
      
      # 7. Build the React app
      - name: Build React app
        run: |
          cd frontend
          npm run build
